### PR TITLE
Fix dl_database bug when record has no data files.

### PR DESCRIPTION
**Pull request by kbrose**
Ref #118

### CODE REVIEW

**Comment by kbrose** [comment]
As far as I can tell there's no unit test for dl_database. Is that on purpose? Can I add one?

**Comment by Dubrzr** [comment]
Hi! Thank you for you PR :+1: Yes you can add one ;)

**Comment by kbrose** [comment]
@Dubrzr done!

**Comment by Dubrzr** [comment]
Thank you very much! @cx1111 will merge with master and create a new release on pypi asap.

**Comment by kbrose** [comment]
Cool, thanks. @cx1111 ASAP timing isn't super critical to me, I've already patched my install to be able to download what I need.

**Comment by cx1111** [comment]
Thank you @kbrose, much appreciated.

**Pull request merged**
