### PR TITLE
Solving issue #154 on MIT-LCP/wfdb-python: plot_wfdb with ecg grid

### PR DESCRIPTION
**Pull request by Gabriel-Azevedo-Ferreira**
The information about the field "sig_units" was not provided before to the function "plot_items".
I solved that issue.

### CODE REVIEW

**Comment by cx1111** [comment]
Hello. Sorry I haven't had time for this project recently. I'm doing a big refactor for the annotations this week, and will check your pulls asap. Thanks for your help.

**Comment by Gabriel-Azevedo-Ferreira** [comment]
Hello,

Thanks for the reply and for looking into my pull requests.

**Comment by tompollard** [comment]
@Gabriel-Azevedo-Ferreira many thanks for the contributions. I'm taking a look at the package and will try to merge some of your pull requests, hopefully without stepping on @cx1111's toes while he works on his refactor. 

It looks like there are a few different sets of changes in this pull request - it would be easier to review and merge if the changes were separated out into separate requests (e.g. "Fix issue X", "Add grid to plot" etc) - so I may end up cherry picking from the commits separately.

**Comment by Gabriel-Azevedo-Ferreira** [comment]
Thank you for taking some time to look into my pull requests. I understand
and agree with you: I should have better split the pull requests into one
task only modifications.

I actually intended to do this, but ended up mixing different changes in
the same pull request by mistake. Hopefully it was not a too difficult to
understand, but if you wish me to re-submit these requests in a more
organized format (1 request =1 modification) let me know.

Thanks!
Gabriel

**Comment by Lucas-Mc** [comment]
I agree with Tom.. Right now, a lot of changes are happening at once and there are three separate pull requests with very similar changes and I don't know which ones to focus on more.

**Pull request closed without merging**
